/* ════════════════════════════════════════════════════════════════════
   R2 · LES MODÈLES DES PROGRAMMES DÉJÀ ACTIFS (tour 20 de Codex)

   ⚠️ FICHIER GÉNÉRÉ par `scripts/r2-remplissage.ts` depuis la composition
   TypeScript (version 1). Ne pas l'éditer à la main :
   `check:programme` exige qu'il soit identique à la génération.

   À coller APRÈS `20261005_r2_prescription.sql`, et seulement après
   l'accord de Louis sur le comparatif. Rejouable.

   Ce qu'il fait : pour chaque étape d'un programme ACTIF qui n'a pas
   encore de modèle pour le lieu de la personne, il écrit ce modèle.
   Ce qu'il ne touche pas : les intentions (préparées, faites, en attente),
   leurs rangs, les journaux, les programmes archivés, les modèles déjà
   écrits (`on conflict do nothing`).
   ════════════════════════════════════════════════════════════════════ */

with banque (lieu, etape, orientation, emplacement, exercice_cle, exercice_nom, fonction, statut, series, mesure,
             reps_min, reps_max, reps_cible, duree_s, repos_s, transition_s, charge_type, unite) as (
  values
    ('salle', 'Full Body', 'force', 0, 'pressecuisses', 'Presse à cuisses', 'squat', 'repere', 5, 'reps', 4, 6, 5, null, 150, 90, 'totale', 'reps'),
    ('salle', 'Full Body', 'force', 1, 'developpecouche', 'Développé couché', 'poussee_horizontale', 'repere', 5, 'reps', 4, 6, 5, null, 150, 90, 'totale', 'reps'),
    ('salle', 'Full Body', 'force', 2, 'rowingassispoulie', 'Rowing assis poulie', 'tirage_horizontal', 'complementaire', 3, 'reps', 8, 12, 10, null, 60, 90, 'totale', 'reps'),
    ('salle', 'Full Body', 'force', 3, 'developpeepaulesmachine', 'Développé épaules machine', 'poussee_verticale', 'complementaire', 3, 'reps', 8, 12, 10, null, 60, 90, 'totale', 'reps'),
    ('salle', 'Full Body', 'force', 4, 'legcurlassis', 'Leg curl assis', 'flexion_genou', 'complementaire', 3, 'reps', 8, 12, 10, null, 60, 90, 'totale', 'reps'),
    ('salle', 'Full Body', 'masse', 0, 'pressecuisses', 'Presse à cuisses', 'squat', 'repere', 4, 'reps', 6, 12, 9, null, 90, 90, 'totale', 'reps'),
    ('salle', 'Full Body', 'masse', 1, 'developpecouche', 'Développé couché', 'poussee_horizontale', 'repere', 4, 'reps', 6, 12, 9, null, 90, 90, 'totale', 'reps'),
    ('salle', 'Full Body', 'masse', 2, 'rowingassispoulie', 'Rowing assis poulie', 'tirage_horizontal', 'complementaire', 3, 'reps', 10, 20, 15, null, 60, 90, 'totale', 'reps'),
    ('salle', 'Full Body', 'masse', 3, 'developpeepaulesmachine', 'Développé épaules machine', 'poussee_verticale', 'complementaire', 3, 'reps', 10, 20, 15, null, 60, 90, 'totale', 'reps'),
    ('salle', 'Full Body', 'masse', 4, 'legcurlassis', 'Leg curl assis', 'flexion_genou', 'complementaire', 3, 'reps', 10, 20, 15, null, 60, 90, 'totale', 'reps'),
    ('salle', 'Full Body', 'general', 0, 'pressecuisses', 'Presse à cuisses', 'squat', 'repere', 3, 'reps', 8, 15, 12, null, 90, 90, 'totale', 'reps'),
    ('salle', 'Full Body', 'general', 1, 'developpecouche', 'Développé couché', 'poussee_horizontale', 'repere', 3, 'reps', 8, 15, 12, null, 90, 90, 'totale', 'reps'),
    ('salle', 'Full Body', 'general', 2, 'rowingassispoulie', 'Rowing assis poulie', 'tirage_horizontal', 'complementaire', 3, 'reps', 8, 15, 12, null, 60, 90, 'totale', 'reps'),
    ('salle', 'Full Body', 'general', 3, 'developpeepaulesmachine', 'Développé épaules machine', 'poussee_verticale', 'complementaire', 3, 'reps', 8, 15, 12, null, 60, 90, 'totale', 'reps'),
    ('salle', 'Full Body', 'general', 4, 'legcurlassis', 'Leg curl assis', 'flexion_genou', 'complementaire', 3, 'reps', 8, 15, 12, null, 60, 90, 'totale', 'reps'),
    ('salle', 'Haut du corps', 'force', 0, 'developpecouche', 'Développé couché', 'poussee_horizontale', 'repere', 5, 'reps', 4, 6, 5, null, 150, 90, 'totale', 'reps'),
    ('salle', 'Haut du corps', 'force', 1, 'tiragepoitrine', 'Tirage poitrine', 'tirage_vertical', 'repere', 5, 'reps', 4, 6, 5, null, 150, 90, 'totale', 'reps'),
    ('salle', 'Haut du corps', 'force', 2, 'developpeepaulesmachine', 'Développé épaules machine', 'poussee_verticale', 'complementaire', 3, 'reps', 8, 12, 10, null, 60, 90, 'totale', 'reps'),
    ('salle', 'Haut du corps', 'force', 3, 'rowingassispoulie', 'Rowing assis poulie', 'tirage_horizontal', 'complementaire', 3, 'reps', 8, 12, 10, null, 60, 90, 'totale', 'reps'),
    ('salle', 'Haut du corps', 'force', 4, 'elevationslaterales', 'Élévations latérales', 'epaule_isolation', 'complementaire', 3, 'reps', 8, 12, 10, null, 45, 90, 'par_haltere', 'reps'),
    ('salle', 'Haut du corps', 'masse', 0, 'developpecouche', 'Développé couché', 'poussee_horizontale', 'repere', 4, 'reps', 6, 12, 9, null, 90, 90, 'totale', 'reps'),
    ('salle', 'Haut du corps', 'masse', 1, 'tiragepoitrine', 'Tirage poitrine', 'tirage_vertical', 'repere', 4, 'reps', 6, 12, 9, null, 60, 90, 'totale', 'reps'),
    ('salle', 'Haut du corps', 'masse', 2, 'developpeepaulesmachine', 'Développé épaules machine', 'poussee_verticale', 'complementaire', 3, 'reps', 10, 20, 15, null, 60, 90, 'totale', 'reps'),
    ('salle', 'Haut du corps', 'masse', 3, 'rowingassispoulie', 'Rowing assis poulie', 'tirage_horizontal', 'complementaire', 3, 'reps', 10, 20, 15, null, 60, 90, 'totale', 'reps'),
    ('salle', 'Haut du corps', 'masse', 4, 'elevationslaterales', 'Élévations latérales', 'epaule_isolation', 'complementaire', 3, 'reps', 10, 20, 15, null, 45, 90, 'par_haltere', 'reps'),
    ('salle', 'Haut du corps', 'general', 0, 'developpecouche', 'Développé couché', 'poussee_horizontale', 'repere', 3, 'reps', 8, 15, 12, null, 90, 90, 'totale', 'reps'),
    ('salle', 'Haut du corps', 'general', 1, 'tiragepoitrine', 'Tirage poitrine', 'tirage_vertical', 'repere', 3, 'reps', 8, 15, 12, null, 60, 90, 'totale', 'reps'),
    ('salle', 'Haut du corps', 'general', 2, 'developpeepaulesmachine', 'Développé épaules machine', 'poussee_verticale', 'complementaire', 3, 'reps', 8, 15, 12, null, 60, 90, 'totale', 'reps'),
    ('salle', 'Haut du corps', 'general', 3, 'rowingassispoulie', 'Rowing assis poulie', 'tirage_horizontal', 'complementaire', 3, 'reps', 8, 15, 12, null, 60, 90, 'totale', 'reps'),
    ('salle', 'Haut du corps', 'general', 4, 'elevationslaterales', 'Élévations latérales', 'epaule_isolation', 'complementaire', 3, 'reps', 8, 15, 12, null, 45, 90, 'par_haltere', 'reps'),
    ('salle', 'Bas du corps', 'force', 0, 'pressecuisses', 'Presse à cuisses', 'squat', 'repere', 5, 'reps', 4, 6, 5, null, 150, 90, 'totale', 'reps'),
    ('salle', 'Bas du corps', 'force', 1, 'souleveterre', 'Soulevé de terre roumain', 'charniere_hanche', 'repere', 5, 'reps', 4, 6, 5, null, 150, 90, 'totale', 'reps'),
    ('salle', 'Bas du corps', 'force', 2, 'legcurlallonge', 'Leg curl allongé', 'flexion_genou', 'complementaire', 3, 'reps', 8, 12, 10, null, 60, 90, 'totale', 'reps'),
    ('salle', 'Bas du corps', 'force', 3, 'legextension', 'Leg extension', 'extension_genou', 'complementaire', 3, 'reps', 8, 12, 10, null, 60, 90, 'totale', 'reps'),
    ('salle', 'Bas du corps', 'force', 4, 'hipthrustmachine', 'Hip thrust machine', 'extension_hanche', 'complementaire', 3, 'reps', 8, 12, 10, null, 75, 90, 'totale', 'reps'),
    ('salle', 'Bas du corps', 'masse', 0, 'pressecuisses', 'Presse à cuisses', 'squat', 'repere', 4, 'reps', 6, 12, 9, null, 90, 90, 'totale', 'reps'),
    ('salle', 'Bas du corps', 'masse', 1, 'souleveterre', 'Soulevé de terre roumain', 'charniere_hanche', 'repere', 4, 'reps', 6, 12, 9, null, 90, 90, 'totale', 'reps'),
    ('salle', 'Bas du corps', 'masse', 2, 'legcurlallonge', 'Leg curl allongé', 'flexion_genou', 'complementaire', 3, 'reps', 10, 20, 15, null, 60, 90, 'totale', 'reps'),
    ('salle', 'Bas du corps', 'masse', 3, 'legextension', 'Leg extension', 'extension_genou', 'complementaire', 3, 'reps', 10, 20, 15, null, 60, 90, 'totale', 'reps'),
    ('salle', 'Bas du corps', 'masse', 4, 'hipthrustmachine', 'Hip thrust machine', 'extension_hanche', 'complementaire', 3, 'reps', 10, 20, 15, null, 75, 90, 'totale', 'reps'),
    ('salle', 'Bas du corps', 'general', 0, 'pressecuisses', 'Presse à cuisses', 'squat', 'repere', 3, 'reps', 8, 15, 12, null, 90, 90, 'totale', 'reps'),
    ('salle', 'Bas du corps', 'general', 1, 'souleveterre', 'Soulevé de terre roumain', 'charniere_hanche', 'repere', 3, 'reps', 8, 15, 12, null, 90, 90, 'totale', 'reps'),
    ('salle', 'Bas du corps', 'general', 2, 'legcurlallonge', 'Leg curl allongé', 'flexion_genou', 'complementaire', 3, 'reps', 8, 15, 12, null, 60, 90, 'totale', 'reps'),
    ('salle', 'Bas du corps', 'general', 3, 'legextension', 'Leg extension', 'extension_genou', 'complementaire', 3, 'reps', 8, 15, 12, null, 60, 90, 'totale', 'reps'),
    ('salle', 'Bas du corps', 'general', 4, 'hipthrustmachine', 'Hip thrust machine', 'extension_hanche', 'complementaire', 3, 'reps', 8, 15, 12, null, 75, 90, 'totale', 'reps'),
    ('salle', 'Push', 'force', 0, 'developpecouche', 'Développé couché', 'poussee_horizontale', 'repere', 5, 'reps', 4, 6, 5, null, 150, 90, 'totale', 'reps'),
    ('salle', 'Push', 'force', 1, 'developpeepaulesmachine', 'Développé épaules machine', 'poussee_verticale', 'repere', 5, 'reps', 4, 6, 5, null, 150, 90, 'totale', 'reps'),
    ('salle', 'Push', 'force', 2, 'developpeinclinehalteres', 'Développé incliné haltères', 'poussee_horizontale', 'complementaire', 3, 'reps', 8, 12, 10, null, 90, 90, 'par_haltere', 'reps'),
    ('salle', 'Push', 'force', 3, 'pecdeck', 'Pec deck', 'ecarte_pectoraux', 'complementaire', 3, 'reps', 8, 12, 10, null, 60, 90, 'totale', 'reps'),
    ('salle', 'Push', 'force', 4, 'elevationslaterales', 'Élévations latérales', 'epaule_isolation', 'complementaire', 3, 'reps', 8, 12, 10, null, 45, 90, 'par_haltere', 'reps'),
    ('salle', 'Push', 'masse', 0, 'developpecouche', 'Développé couché', 'poussee_horizontale', 'repere', 4, 'reps', 6, 12, 9, null, 90, 90, 'totale', 'reps'),
    ('salle', 'Push', 'masse', 1, 'developpeepaulesmachine', 'Développé épaules machine', 'poussee_verticale', 'repere', 4, 'reps', 6, 12, 9, null, 60, 90, 'totale', 'reps'),
    ('salle', 'Push', 'masse', 2, 'developpeinclinehalteres', 'Développé incliné haltères', 'poussee_horizontale', 'complementaire', 3, 'reps', 10, 20, 15, null, 90, 90, 'par_haltere', 'reps'),
    ('salle', 'Push', 'masse', 3, 'pecdeck', 'Pec deck', 'ecarte_pectoraux', 'complementaire', 3, 'reps', 10, 20, 15, null, 60, 90, 'totale', 'reps'),
    ('salle', 'Push', 'masse', 4, 'elevationslaterales', 'Élévations latérales', 'epaule_isolation', 'complementaire', 3, 'reps', 10, 20, 15, null, 45, 90, 'par_haltere', 'reps'),
    ('salle', 'Push', 'general', 0, 'developpecouche', 'Développé couché', 'poussee_horizontale', 'repere', 3, 'reps', 8, 15, 12, null, 90, 90, 'totale', 'reps'),
    ('salle', 'Push', 'general', 1, 'developpeepaulesmachine', 'Développé épaules machine', 'poussee_verticale', 'repere', 3, 'reps', 8, 15, 12, null, 60, 90, 'totale', 'reps'),
    ('salle', 'Push', 'general', 2, 'developpeinclinehalteres', 'Développé incliné haltères', 'poussee_horizontale', 'complementaire', 3, 'reps', 8, 15, 12, null, 90, 90, 'par_haltere', 'reps'),
    ('salle', 'Push', 'general', 3, 'pecdeck', 'Pec deck', 'ecarte_pectoraux', 'complementaire', 3, 'reps', 8, 15, 12, null, 60, 90, 'totale', 'reps'),
    ('salle', 'Push', 'general', 4, 'elevationslaterales', 'Élévations latérales', 'epaule_isolation', 'complementaire', 3, 'reps', 8, 15, 12, null, 45, 90, 'par_haltere', 'reps'),
    ('salle', 'Pull', 'force', 0, 'tiragepoitrine', 'Tirage poitrine', 'tirage_vertical', 'repere', 5, 'reps', 4, 6, 5, null, 150, 90, 'totale', 'reps'),
    ('salle', 'Pull', 'force', 1, 'rowingassispoulie', 'Rowing assis poulie', 'tirage_horizontal', 'repere', 5, 'reps', 4, 6, 5, null, 150, 90, 'totale', 'reps'),
    ('salle', 'Pull', 'force', 2, 'rowingunilateralhaltere', 'Rowing haltère', 'tirage_horizontal', 'complementaire', 3, 'reps', 8, 12, 10, null, 60, 90, 'par_haltere', 'par bras'),
    ('salle', 'Pull', 'force', 3, 'facepullpoulie', 'Face pull poulie', 'arriere_epaule', 'complementaire', 3, 'reps', 8, 12, 10, null, 60, 90, 'totale', 'reps'),
    ('salle', 'Pull', 'force', 4, 'curlbarreez', 'Curl barre EZ', 'biceps', 'complementaire', 3, 'reps', 8, 12, 10, null, 60, 90, 'totale', 'reps'),
    ('salle', 'Pull', 'masse', 0, 'tiragepoitrine', 'Tirage poitrine', 'tirage_vertical', 'repere', 4, 'reps', 6, 12, 9, null, 60, 90, 'totale', 'reps'),
    ('salle', 'Pull', 'masse', 1, 'rowingassispoulie', 'Rowing assis poulie', 'tirage_horizontal', 'repere', 4, 'reps', 6, 12, 9, null, 60, 90, 'totale', 'reps'),
    ('salle', 'Pull', 'masse', 2, 'rowingunilateralhaltere', 'Rowing haltère', 'tirage_horizontal', 'complementaire', 3, 'reps', 10, 20, 15, null, 60, 90, 'par_haltere', 'par bras'),
    ('salle', 'Pull', 'masse', 3, 'facepullpoulie', 'Face pull poulie', 'arriere_epaule', 'complementaire', 3, 'reps', 10, 20, 15, null, 60, 90, 'totale', 'reps'),
    ('salle', 'Pull', 'masse', 4, 'curlbarreez', 'Curl barre EZ', 'biceps', 'complementaire', 3, 'reps', 10, 20, 15, null, 60, 90, 'totale', 'reps'),
    ('salle', 'Pull', 'general', 0, 'tiragepoitrine', 'Tirage poitrine', 'tirage_vertical', 'repere', 3, 'reps', 8, 15, 12, null, 60, 90, 'totale', 'reps'),
    ('salle', 'Pull', 'general', 1, 'rowingassispoulie', 'Rowing assis poulie', 'tirage_horizontal', 'repere', 3, 'reps', 8, 15, 12, null, 60, 90, 'totale', 'reps'),
    ('salle', 'Pull', 'general', 2, 'rowingunilateralhaltere', 'Rowing haltère', 'tirage_horizontal', 'complementaire', 3, 'reps', 8, 15, 12, null, 60, 90, 'par_haltere', 'par bras'),
    ('salle', 'Pull', 'general', 3, 'facepullpoulie', 'Face pull poulie', 'arriere_epaule', 'complementaire', 3, 'reps', 8, 15, 12, null, 60, 90, 'totale', 'reps'),
    ('salle', 'Pull', 'general', 4, 'curlbarreez', 'Curl barre EZ', 'biceps', 'complementaire', 3, 'reps', 8, 15, 12, null, 60, 90, 'totale', 'reps'),
    ('salle', 'Cardio / HIIT', 'force', 0, 'coursetapis', 'Tapis de course', 'cardio', 'complementaire', 1, 'duree', null, null, null, 1200, 60, 60, null, ''),
    ('salle', 'Cardio / HIIT', 'force', 1, 'veloappartement', 'Vélo', 'cardio', 'complementaire', 1, 'duree', null, null, null, 900, 60, 60, null, ''),
    ('salle', 'Cardio / HIIT', 'force', 2, 'rameur', 'Rameur', 'cardio', 'complementaire', 1, 'duree', null, null, null, 600, 60, 60, null, ''),
    ('salle', 'Cardio / HIIT', 'force', 3, 'burpees', 'Burpees', 'cardio', 'complementaire', 4, 'reps', 15, 15, 15, null, 45, 90, 'poids_du_corps', 'reps'),
    ('salle', 'Cardio / HIIT', 'force', 4, 'mountainclimbers', 'Mountain climbers', 'cardio', 'complementaire', 4, 'duree', null, null, null, 30, 30, 60, null, ''),
    ('salle', 'Cardio / HIIT', 'masse', 0, 'coursetapis', 'Tapis de course', 'cardio', 'complementaire', 1, 'duree', null, null, null, 1200, 60, 60, null, ''),
    ('salle', 'Cardio / HIIT', 'masse', 1, 'veloappartement', 'Vélo', 'cardio', 'complementaire', 1, 'duree', null, null, null, 900, 60, 60, null, ''),
    ('salle', 'Cardio / HIIT', 'masse', 2, 'rameur', 'Rameur', 'cardio', 'complementaire', 1, 'duree', null, null, null, 600, 60, 60, null, ''),
    ('salle', 'Cardio / HIIT', 'masse', 3, 'burpees', 'Burpees', 'cardio', 'complementaire', 4, 'reps', 15, 15, 15, null, 45, 90, 'poids_du_corps', 'reps'),
    ('salle', 'Cardio / HIIT', 'masse', 4, 'mountainclimbers', 'Mountain climbers', 'cardio', 'complementaire', 4, 'duree', null, null, null, 30, 30, 60, null, ''),
    ('salle', 'Cardio / HIIT', 'general', 0, 'coursetapis', 'Tapis de course', 'cardio', 'complementaire', 1, 'duree', null, null, null, 1200, 60, 60, null, ''),
    ('salle', 'Cardio / HIIT', 'general', 1, 'veloappartement', 'Vélo', 'cardio', 'complementaire', 1, 'duree', null, null, null, 900, 60, 60, null, ''),
    ('salle', 'Cardio / HIIT', 'general', 2, 'rameur', 'Rameur', 'cardio', 'complementaire', 1, 'duree', null, null, null, 600, 60, 60, null, ''),
    ('salle', 'Cardio / HIIT', 'general', 3, 'burpees', 'Burpees', 'cardio', 'complementaire', 4, 'reps', 15, 15, 15, null, 45, 90, 'poids_du_corps', 'reps'),
    ('salle', 'Cardio / HIIT', 'general', 4, 'mountainclimbers', 'Mountain climbers', 'cardio', 'complementaire', 4, 'duree', null, null, null, 30, 30, 60, null, ''),
    ('halteres', 'Full Body', 'force', 0, 'gobletsquat', 'Goblet squat', 'squat', 'repere', 5, 'reps', 4, 6, 5, null, 150, 90, 'par_haltere', 'reps'),
    ('halteres', 'Full Body', 'force', 1, 'developpecouchehalteres', 'Développé couché haltères', 'poussee_horizontale', 'repere', 5, 'reps', 4, 6, 5, null, 150, 90, 'par_haltere', 'reps'),
    ('halteres', 'Full Body', 'force', 2, 'rowingunilateralhaltere', 'Rowing haltère', 'tirage_horizontal', 'complementaire', 3, 'reps', 8, 12, 10, null, 60, 90, 'par_haltere', 'par bras'),
    ('halteres', 'Full Body', 'force', 3, 'militaire', 'Développé militaire haltères', 'poussee_verticale', 'complementaire', 3, 'reps', 8, 12, 10, null, 75, 90, 'par_haltere', 'reps'),
    ('halteres', 'Full Body', 'force', 4, 'fentes', 'Fentes', 'unilateral_jambe', 'complementaire', 3, 'reps', 8, 12, 10, null, 60, 90, 'poids_du_corps', 'par jambe'),
    ('halteres', 'Full Body', 'masse', 0, 'gobletsquat', 'Goblet squat', 'squat', 'repere', 4, 'reps', 6, 12, 9, null, 60, 90, 'par_haltere', 'reps'),
    ('halteres', 'Full Body', 'masse', 1, 'developpecouchehalteres', 'Développé couché haltères', 'poussee_horizontale', 'repere', 4, 'reps', 6, 12, 9, null, 90, 90, 'par_haltere', 'reps'),
    ('halteres', 'Full Body', 'masse', 2, 'rowingunilateralhaltere', 'Rowing haltère', 'tirage_horizontal', 'complementaire', 3, 'reps', 10, 20, 15, null, 60, 90, 'par_haltere', 'par bras'),
    ('halteres', 'Full Body', 'masse', 3, 'militaire', 'Développé militaire haltères', 'poussee_verticale', 'complementaire', 3, 'reps', 10, 20, 15, null, 75, 90, 'par_haltere', 'reps'),
    ('halteres', 'Full Body', 'masse', 4, 'fentes', 'Fentes', 'unilateral_jambe', 'complementaire', 3, 'reps', 10, 20, 15, null, 60, 90, 'poids_du_corps', 'par jambe'),
    ('halteres', 'Full Body', 'general', 0, 'gobletsquat', 'Goblet squat', 'squat', 'repere', 3, 'reps', 8, 15, 12, null, 60, 90, 'par_haltere', 'reps'),
    ('halteres', 'Full Body', 'general', 1, 'developpecouchehalteres', 'Développé couché haltères', 'poussee_horizontale', 'repere', 3, 'reps', 8, 15, 12, null, 90, 90, 'par_haltere', 'reps'),
    ('halteres', 'Full Body', 'general', 2, 'rowingunilateralhaltere', 'Rowing haltère', 'tirage_horizontal', 'complementaire', 3, 'reps', 8, 15, 12, null, 60, 90, 'par_haltere', 'par bras'),
    ('halteres', 'Full Body', 'general', 3, 'militaire', 'Développé militaire haltères', 'poussee_verticale', 'complementaire', 3, 'reps', 8, 15, 12, null, 75, 90, 'par_haltere', 'reps'),
    ('halteres', 'Full Body', 'general', 4, 'fentes', 'Fentes', 'unilateral_jambe', 'complementaire', 3, 'reps', 8, 15, 12, null, 60, 90, 'poids_du_corps', 'par jambe'),
    ('halteres', 'Haut du corps', 'force', 0, 'developpecouchehalteres', 'Développé couché haltères', 'poussee_horizontale', 'repere', 5, 'reps', 4, 6, 5, null, 150, 90, 'par_haltere', 'reps'),
    ('halteres', 'Haut du corps', 'force', 1, 'rowingunilateralhaltere', 'Rowing haltère', 'tirage_horizontal', 'repere', 5, 'reps', 4, 6, 5, null, 150, 90, 'par_haltere', 'par bras'),
    ('halteres', 'Haut du corps', 'force', 2, 'militaire', 'Développé militaire haltères', 'poussee_verticale', 'complementaire', 3, 'reps', 8, 12, 10, null, 75, 90, 'par_haltere', 'reps'),
    ('halteres', 'Haut du corps', 'force', 3, 'elevationslaterales', 'Élévations latérales', 'epaule_isolation', 'complementaire', 3, 'reps', 8, 12, 10, null, 45, 90, 'par_haltere', 'reps'),
    ('halteres', 'Haut du corps', 'force', 4, 'curl', 'Curl haltères', 'biceps', 'complementaire', 3, 'reps', 8, 12, 10, null, 45, 90, 'par_haltere', 'reps'),
    ('halteres', 'Haut du corps', 'masse', 0, 'developpecouchehalteres', 'Développé couché haltères', 'poussee_horizontale', 'repere', 4, 'reps', 6, 12, 9, null, 90, 90, 'par_haltere', 'reps'),
    ('halteres', 'Haut du corps', 'masse', 1, 'rowingunilateralhaltere', 'Rowing haltère', 'tirage_horizontal', 'repere', 4, 'reps', 6, 12, 9, null, 60, 90, 'par_haltere', 'par bras'),
    ('halteres', 'Haut du corps', 'masse', 2, 'militaire', 'Développé militaire haltères', 'poussee_verticale', 'complementaire', 3, 'reps', 10, 20, 15, null, 75, 90, 'par_haltere', 'reps'),
    ('halteres', 'Haut du corps', 'masse', 3, 'elevationslaterales', 'Élévations latérales', 'epaule_isolation', 'complementaire', 3, 'reps', 10, 20, 15, null, 45, 90, 'par_haltere', 'reps'),
    ('halteres', 'Haut du corps', 'masse', 4, 'curl', 'Curl haltères', 'biceps', 'complementaire', 3, 'reps', 10, 20, 15, null, 45, 90, 'par_haltere', 'reps'),
    ('halteres', 'Haut du corps', 'general', 0, 'developpecouchehalteres', 'Développé couché haltères', 'poussee_horizontale', 'repere', 3, 'reps', 8, 15, 12, null, 90, 90, 'par_haltere', 'reps'),
    ('halteres', 'Haut du corps', 'general', 1, 'rowingunilateralhaltere', 'Rowing haltère', 'tirage_horizontal', 'repere', 3, 'reps', 8, 15, 12, null, 60, 90, 'par_haltere', 'par bras'),
    ('halteres', 'Haut du corps', 'general', 2, 'militaire', 'Développé militaire haltères', 'poussee_verticale', 'complementaire', 3, 'reps', 8, 15, 12, null, 75, 90, 'par_haltere', 'reps'),
    ('halteres', 'Haut du corps', 'general', 3, 'elevationslaterales', 'Élévations latérales', 'epaule_isolation', 'complementaire', 3, 'reps', 8, 15, 12, null, 45, 90, 'par_haltere', 'reps'),
    ('halteres', 'Haut du corps', 'general', 4, 'curl', 'Curl haltères', 'biceps', 'complementaire', 3, 'reps', 8, 15, 12, null, 45, 90, 'par_haltere', 'reps'),
    ('halteres', 'Bas du corps', 'force', 0, 'gobletsquat', 'Goblet squat', 'squat', 'repere', 5, 'reps', 4, 6, 5, null, 150, 90, 'par_haltere', 'reps'),
    ('halteres', 'Bas du corps', 'force', 1, 'squatbulgare', 'Squat bulgare', 'unilateral_jambe', 'repere', 5, 'reps', 4, 6, 5, null, 150, 90, 'poids_du_corps', 'par jambe'),
    ('halteres', 'Bas du corps', 'force', 2, 'fentes', 'Fentes', 'unilateral_jambe', 'complementaire', 3, 'reps', 8, 12, 10, null, 60, 90, 'poids_du_corps', 'par jambe'),
    ('halteres', 'Bas du corps', 'force', 3, 'hipthrust', 'Pont fessier', 'extension_hanche', 'complementaire', 3, 'reps', 8, 12, 10, null, 60, 90, 'poids_du_corps', 'reps'),
    ('halteres', 'Bas du corps', 'force', 4, 'mollets', 'Mollets', 'mollets', 'complementaire', 3, 'reps', 8, 12, 10, null, 45, 90, 'poids_du_corps', 'reps'),
    ('halteres', 'Bas du corps', 'masse', 0, 'gobletsquat', 'Goblet squat', 'squat', 'repere', 4, 'reps', 6, 12, 9, null, 60, 90, 'par_haltere', 'reps'),
    ('halteres', 'Bas du corps', 'masse', 1, 'squatbulgare', 'Squat bulgare', 'unilateral_jambe', 'repere', 4, 'reps', 6, 12, 9, null, 60, 90, 'poids_du_corps', 'par jambe'),
    ('halteres', 'Bas du corps', 'masse', 2, 'fentes', 'Fentes', 'unilateral_jambe', 'complementaire', 3, 'reps', 10, 20, 15, null, 60, 90, 'poids_du_corps', 'par jambe'),
    ('halteres', 'Bas du corps', 'masse', 3, 'hipthrust', 'Pont fessier', 'extension_hanche', 'complementaire', 3, 'reps', 10, 20, 15, null, 60, 90, 'poids_du_corps', 'reps'),
    ('halteres', 'Bas du corps', 'masse', 4, 'mollets', 'Mollets', 'mollets', 'complementaire', 3, 'reps', 10, 20, 15, null, 45, 90, 'poids_du_corps', 'reps'),
    ('halteres', 'Bas du corps', 'general', 0, 'gobletsquat', 'Goblet squat', 'squat', 'repere', 3, 'reps', 8, 15, 12, null, 60, 90, 'par_haltere', 'reps'),
    ('halteres', 'Bas du corps', 'general', 1, 'squatbulgare', 'Squat bulgare', 'unilateral_jambe', 'repere', 3, 'reps', 8, 15, 12, null, 60, 90, 'poids_du_corps', 'par jambe'),
    ('halteres', 'Bas du corps', 'general', 2, 'fentes', 'Fentes', 'unilateral_jambe', 'complementaire', 3, 'reps', 8, 15, 12, null, 60, 90, 'poids_du_corps', 'par jambe'),
    ('halteres', 'Bas du corps', 'general', 3, 'hipthrust', 'Pont fessier', 'extension_hanche', 'complementaire', 3, 'reps', 8, 15, 12, null, 60, 90, 'poids_du_corps', 'reps'),
    ('halteres', 'Bas du corps', 'general', 4, 'mollets', 'Mollets', 'mollets', 'complementaire', 3, 'reps', 8, 15, 12, null, 45, 90, 'poids_du_corps', 'reps'),
    ('halteres', 'Push', 'force', 0, 'developpecouchehalteres', 'Développé couché haltères', 'poussee_horizontale', 'repere', 5, 'reps', 4, 6, 5, null, 150, 90, 'par_haltere', 'reps'),
    ('halteres', 'Push', 'force', 1, 'militaire', 'Développé militaire haltères', 'poussee_verticale', 'repere', 5, 'reps', 4, 6, 5, null, 150, 90, 'par_haltere', 'reps'),
    ('halteres', 'Push', 'force', 2, 'developpeinclinehalteres', 'Développé incliné haltères', 'poussee_horizontale', 'complementaire', 3, 'reps', 8, 12, 10, null, 90, 90, 'par_haltere', 'reps'),
    ('halteres', 'Push', 'force', 3, 'elevationslaterales', 'Élévations latérales', 'epaule_isolation', 'complementaire', 3, 'reps', 8, 12, 10, null, 45, 90, 'par_haltere', 'reps'),
    ('halteres', 'Push', 'force', 4, 'extensiontricepshaltere', 'Extension triceps haltère', 'triceps', 'complementaire', 3, 'reps', 8, 12, 10, null, 45, 90, 'par_haltere', 'reps'),
    ('halteres', 'Push', 'masse', 0, 'developpecouchehalteres', 'Développé couché haltères', 'poussee_horizontale', 'repere', 4, 'reps', 6, 12, 9, null, 90, 90, 'par_haltere', 'reps'),
    ('halteres', 'Push', 'masse', 1, 'militaire', 'Développé militaire haltères', 'poussee_verticale', 'repere', 4, 'reps', 6, 12, 9, null, 75, 90, 'par_haltere', 'reps'),
    ('halteres', 'Push', 'masse', 2, 'developpeinclinehalteres', 'Développé incliné haltères', 'poussee_horizontale', 'complementaire', 3, 'reps', 10, 20, 15, null, 90, 90, 'par_haltere', 'reps'),
    ('halteres', 'Push', 'masse', 3, 'elevationslaterales', 'Élévations latérales', 'epaule_isolation', 'complementaire', 3, 'reps', 10, 20, 15, null, 45, 90, 'par_haltere', 'reps'),
    ('halteres', 'Push', 'masse', 4, 'extensiontricepshaltere', 'Extension triceps haltère', 'triceps', 'complementaire', 3, 'reps', 10, 20, 15, null, 45, 90, 'par_haltere', 'reps'),
    ('halteres', 'Push', 'general', 0, 'developpecouchehalteres', 'Développé couché haltères', 'poussee_horizontale', 'repere', 3, 'reps', 8, 15, 12, null, 90, 90, 'par_haltere', 'reps'),
    ('halteres', 'Push', 'general', 1, 'militaire', 'Développé militaire haltères', 'poussee_verticale', 'repere', 3, 'reps', 8, 15, 12, null, 75, 90, 'par_haltere', 'reps'),
    ('halteres', 'Push', 'general', 2, 'developpeinclinehalteres', 'Développé incliné haltères', 'poussee_horizontale', 'complementaire', 3, 'reps', 8, 15, 12, null, 90, 90, 'par_haltere', 'reps'),
    ('halteres', 'Push', 'general', 3, 'elevationslaterales', 'Élévations latérales', 'epaule_isolation', 'complementaire', 3, 'reps', 8, 15, 12, null, 45, 90, 'par_haltere', 'reps'),
    ('halteres', 'Push', 'general', 4, 'extensiontricepshaltere', 'Extension triceps haltère', 'triceps', 'complementaire', 3, 'reps', 8, 15, 12, null, 45, 90, 'par_haltere', 'reps'),
    ('halteres', 'Pull', 'force', 0, 'rowingunilateralhaltere', 'Rowing haltère', 'tirage_horizontal', 'repere', 5, 'reps', 4, 6, 5, null, 150, 90, 'par_haltere', 'par bras'),
    ('halteres', 'Pull', 'force', 1, 'rowingbustepenchehalteres', 'Rowing buste penché haltères', 'tirage_horizontal', 'repere', 5, 'reps', 4, 6, 5, null, 150, 90, 'par_haltere', 'reps'),
    ('halteres', 'Pull', 'force', 2, 'oiseauhalteres', 'Oiseau haltères', 'arriere_epaule', 'complementaire', 3, 'reps', 8, 12, 10, null, 45, 90, 'par_haltere', 'reps'),
    ('halteres', 'Pull', 'force', 3, 'curl', 'Curl haltères', 'biceps', 'complementaire', 3, 'reps', 8, 12, 10, null, 45, 90, 'par_haltere', 'reps'),
    ('halteres', 'Pull', 'force', 4, 'curlmarteau', 'Curl marteau', 'biceps', 'complementaire', 3, 'reps', 8, 12, 10, null, 45, 90, 'par_haltere', 'reps'),
    ('halteres', 'Pull', 'masse', 0, 'rowingunilateralhaltere', 'Rowing haltère', 'tirage_horizontal', 'repere', 4, 'reps', 6, 12, 9, null, 60, 90, 'par_haltere', 'par bras'),
    ('halteres', 'Pull', 'masse', 1, 'rowingbustepenchehalteres', 'Rowing buste penché haltères', 'tirage_horizontal', 'repere', 4, 'reps', 6, 12, 9, null, 75, 90, 'par_haltere', 'reps'),
    ('halteres', 'Pull', 'masse', 2, 'oiseauhalteres', 'Oiseau haltères', 'arriere_epaule', 'complementaire', 3, 'reps', 10, 20, 15, null, 45, 90, 'par_haltere', 'reps'),
    ('halteres', 'Pull', 'masse', 3, 'curl', 'Curl haltères', 'biceps', 'complementaire', 3, 'reps', 10, 20, 15, null, 45, 90, 'par_haltere', 'reps'),
    ('halteres', 'Pull', 'masse', 4, 'curlmarteau', 'Curl marteau', 'biceps', 'complementaire', 3, 'reps', 10, 20, 15, null, 45, 90, 'par_haltere', 'reps'),
    ('halteres', 'Pull', 'general', 0, 'rowingunilateralhaltere', 'Rowing haltère', 'tirage_horizontal', 'repere', 3, 'reps', 8, 15, 12, null, 60, 90, 'par_haltere', 'par bras'),
    ('halteres', 'Pull', 'general', 1, 'rowingbustepenchehalteres', 'Rowing buste penché haltères', 'tirage_horizontal', 'repere', 3, 'reps', 8, 15, 12, null, 75, 90, 'par_haltere', 'reps'),
    ('halteres', 'Pull', 'general', 2, 'oiseauhalteres', 'Oiseau haltères', 'arriere_epaule', 'complementaire', 3, 'reps', 8, 15, 12, null, 45, 90, 'par_haltere', 'reps'),
    ('halteres', 'Pull', 'general', 3, 'curl', 'Curl haltères', 'biceps', 'complementaire', 3, 'reps', 8, 15, 12, null, 45, 90, 'par_haltere', 'reps'),
    ('halteres', 'Pull', 'general', 4, 'curlmarteau', 'Curl marteau', 'biceps', 'complementaire', 3, 'reps', 8, 15, 12, null, 45, 90, 'par_haltere', 'reps'),
    ('halteres', 'Cardio / HIIT', 'force', 0, 'burpees', 'Burpees', 'cardio', 'complementaire', 4, 'reps', 15, 15, 15, null, 45, 90, 'poids_du_corps', 'reps'),
    ('halteres', 'Cardio / HIIT', 'force', 1, 'skaters', 'Skaters', 'cardio', 'complementaire', 5, 'duree', null, null, null, 40, 30, 60, null, ''),
    ('halteres', 'Cardio / HIIT', 'force', 2, 'mountainclimbers', 'Mountain climbers', 'cardio', 'complementaire', 4, 'duree', null, null, null, 30, 30, 60, null, ''),
    ('halteres', 'Cardio / HIIT', 'force', 3, 'jumpingjacks', 'Jumping jacks', 'cardio', 'complementaire', 4, 'duree', null, null, null, 40, 20, 60, null, ''),
    ('halteres', 'Cardio / HIIT', 'force', 4, 'squatsaute', 'Squats sautés', 'pliometrie', 'complementaire', 4, 'reps', 20, 20, 20, null, 45, 90, 'poids_du_corps', 'reps'),
    ('halteres', 'Cardio / HIIT', 'masse', 0, 'burpees', 'Burpees', 'cardio', 'complementaire', 4, 'reps', 15, 15, 15, null, 45, 90, 'poids_du_corps', 'reps'),
    ('halteres', 'Cardio / HIIT', 'masse', 1, 'skaters', 'Skaters', 'cardio', 'complementaire', 5, 'duree', null, null, null, 40, 30, 60, null, ''),
    ('halteres', 'Cardio / HIIT', 'masse', 2, 'mountainclimbers', 'Mountain climbers', 'cardio', 'complementaire', 4, 'duree', null, null, null, 30, 30, 60, null, ''),
    ('halteres', 'Cardio / HIIT', 'masse', 3, 'jumpingjacks', 'Jumping jacks', 'cardio', 'complementaire', 4, 'duree', null, null, null, 40, 20, 60, null, ''),
    ('halteres', 'Cardio / HIIT', 'masse', 4, 'squatsaute', 'Squats sautés', 'pliometrie', 'complementaire', 4, 'reps', 20, 20, 20, null, 45, 90, 'poids_du_corps', 'reps'),
    ('halteres', 'Cardio / HIIT', 'general', 0, 'burpees', 'Burpees', 'cardio', 'complementaire', 4, 'reps', 15, 15, 15, null, 45, 90, 'poids_du_corps', 'reps'),
    ('halteres', 'Cardio / HIIT', 'general', 1, 'skaters', 'Skaters', 'cardio', 'complementaire', 5, 'duree', null, null, null, 40, 30, 60, null, ''),
    ('halteres', 'Cardio / HIIT', 'general', 2, 'mountainclimbers', 'Mountain climbers', 'cardio', 'complementaire', 4, 'duree', null, null, null, 30, 30, 60, null, ''),
    ('halteres', 'Cardio / HIIT', 'general', 3, 'jumpingjacks', 'Jumping jacks', 'cardio', 'complementaire', 4, 'duree', null, null, null, 40, 20, 60, null, ''),
    ('halteres', 'Cardio / HIIT', 'general', 4, 'squatsaute', 'Squats sautés', 'pliometrie', 'complementaire', 4, 'reps', 20, 20, 20, null, 45, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Full Body', 'force', 0, 'squat', 'Squat', 'squat', 'repere', 5, 'reps', 4, 6, 5, null, 150, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Full Body', 'force', 1, 'pompes', 'Pompes', 'poussee_horizontale', 'repere', 5, 'reps', 4, 6, 5, null, 150, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Full Body', 'force', 2, 'fentes', 'Fentes', 'unilateral_jambe', 'complementaire', 3, 'reps', 8, 12, 10, null, 60, 90, 'poids_du_corps', 'par jambe'),
    ('poids', 'Full Body', 'force', 3, 'planche', 'Gainage', 'gainage', 'complementaire', 3, 'duree', null, null, null, 45, 45, 60, 'poids_du_corps', ''),
    ('poids', 'Full Body', 'force', 4, 'dips', 'Dips sur chaise', 'triceps', 'complementaire', 3, 'reps', 8, 12, 10, null, 60, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Full Body', 'masse', 0, 'squat', 'Squat', 'squat', 'repere', 4, 'reps', 6, 12, 9, null, 60, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Full Body', 'masse', 1, 'pompes', 'Pompes', 'poussee_horizontale', 'repere', 4, 'reps', 6, 12, 9, null, 60, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Full Body', 'masse', 2, 'fentes', 'Fentes', 'unilateral_jambe', 'complementaire', 3, 'reps', 10, 20, 15, null, 60, 90, 'poids_du_corps', 'par jambe'),
    ('poids', 'Full Body', 'masse', 3, 'planche', 'Gainage', 'gainage', 'complementaire', 3, 'duree', null, null, null, 45, 45, 60, 'poids_du_corps', ''),
    ('poids', 'Full Body', 'masse', 4, 'dips', 'Dips sur chaise', 'triceps', 'complementaire', 3, 'reps', 10, 20, 15, null, 60, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Full Body', 'general', 0, 'squat', 'Squat', 'squat', 'repere', 3, 'reps', 8, 15, 12, null, 60, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Full Body', 'general', 1, 'pompes', 'Pompes', 'poussee_horizontale', 'repere', 3, 'reps', 8, 15, 12, null, 60, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Full Body', 'general', 2, 'fentes', 'Fentes', 'unilateral_jambe', 'complementaire', 3, 'reps', 8, 15, 12, null, 60, 90, 'poids_du_corps', 'par jambe'),
    ('poids', 'Full Body', 'general', 3, 'planche', 'Gainage', 'gainage', 'complementaire', 3, 'duree', null, null, null, 45, 45, 60, 'poids_du_corps', ''),
    ('poids', 'Full Body', 'general', 4, 'dips', 'Dips sur chaise', 'triceps', 'complementaire', 3, 'reps', 8, 15, 12, null, 60, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Haut du corps', 'force', 0, 'pompes', 'Pompes', 'poussee_horizontale', 'repere', 5, 'reps', 4, 6, 5, null, 150, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Haut du corps', 'force', 1, 'pikepushups', 'Pike push-ups', 'poussee_verticale', 'repere', 5, 'reps', 4, 6, 5, null, 150, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Haut du corps', 'force', 2, 'dips', 'Dips sur chaise', 'triceps', 'complementaire', 3, 'reps', 8, 12, 10, null, 60, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Haut du corps', 'force', 3, 'pompesinclinees', 'Pompes inclinées', 'poussee_horizontale', 'complementaire', 3, 'reps', 8, 12, 10, null, 60, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Haut du corps', 'force', 4, 'superman', 'Superman', 'extension_tronc', 'complementaire', 3, 'reps', 8, 12, 10, null, 45, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Haut du corps', 'masse', 0, 'pompes', 'Pompes', 'poussee_horizontale', 'repere', 4, 'reps', 6, 12, 9, null, 60, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Haut du corps', 'masse', 1, 'pikepushups', 'Pike push-ups', 'poussee_verticale', 'repere', 4, 'reps', 6, 12, 9, null, 60, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Haut du corps', 'masse', 2, 'dips', 'Dips sur chaise', 'triceps', 'complementaire', 3, 'reps', 10, 20, 15, null, 60, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Haut du corps', 'masse', 3, 'pompesinclinees', 'Pompes inclinées', 'poussee_horizontale', 'complementaire', 3, 'reps', 10, 20, 15, null, 60, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Haut du corps', 'masse', 4, 'superman', 'Superman', 'extension_tronc', 'complementaire', 3, 'reps', 10, 20, 15, null, 45, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Haut du corps', 'general', 0, 'pompes', 'Pompes', 'poussee_horizontale', 'repere', 3, 'reps', 8, 15, 12, null, 60, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Haut du corps', 'general', 1, 'pikepushups', 'Pike push-ups', 'poussee_verticale', 'repere', 3, 'reps', 8, 15, 12, null, 60, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Haut du corps', 'general', 2, 'dips', 'Dips sur chaise', 'triceps', 'complementaire', 3, 'reps', 8, 15, 12, null, 60, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Haut du corps', 'general', 3, 'pompesinclinees', 'Pompes inclinées', 'poussee_horizontale', 'complementaire', 3, 'reps', 8, 15, 12, null, 60, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Haut du corps', 'general', 4, 'superman', 'Superman', 'extension_tronc', 'complementaire', 3, 'reps', 8, 15, 12, null, 45, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Bas du corps', 'force', 0, 'squat', 'Squat', 'squat', 'repere', 5, 'reps', 4, 6, 5, null, 150, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Bas du corps', 'force', 1, 'squatbulgare', 'Squat bulgare', 'unilateral_jambe', 'repere', 5, 'reps', 4, 6, 5, null, 150, 90, 'poids_du_corps', 'par jambe'),
    ('poids', 'Bas du corps', 'force', 2, 'fentes', 'Fentes', 'unilateral_jambe', 'complementaire', 3, 'reps', 8, 12, 10, null, 60, 90, 'poids_du_corps', 'par jambe'),
    ('poids', 'Bas du corps', 'force', 3, 'hipthrust', 'Pont fessier', 'extension_hanche', 'complementaire', 3, 'reps', 8, 12, 10, null, 60, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Bas du corps', 'force', 4, 'mollets', 'Mollets', 'mollets', 'complementaire', 3, 'reps', 8, 12, 10, null, 45, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Bas du corps', 'masse', 0, 'squat', 'Squat', 'squat', 'repere', 4, 'reps', 6, 12, 9, null, 60, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Bas du corps', 'masse', 1, 'squatbulgare', 'Squat bulgare', 'unilateral_jambe', 'repere', 4, 'reps', 6, 12, 9, null, 60, 90, 'poids_du_corps', 'par jambe'),
    ('poids', 'Bas du corps', 'masse', 2, 'fentes', 'Fentes', 'unilateral_jambe', 'complementaire', 3, 'reps', 10, 20, 15, null, 60, 90, 'poids_du_corps', 'par jambe'),
    ('poids', 'Bas du corps', 'masse', 3, 'hipthrust', 'Pont fessier', 'extension_hanche', 'complementaire', 3, 'reps', 10, 20, 15, null, 60, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Bas du corps', 'masse', 4, 'mollets', 'Mollets', 'mollets', 'complementaire', 3, 'reps', 10, 20, 15, null, 45, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Bas du corps', 'general', 0, 'squat', 'Squat', 'squat', 'repere', 3, 'reps', 8, 15, 12, null, 60, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Bas du corps', 'general', 1, 'squatbulgare', 'Squat bulgare', 'unilateral_jambe', 'repere', 3, 'reps', 8, 15, 12, null, 60, 90, 'poids_du_corps', 'par jambe'),
    ('poids', 'Bas du corps', 'general', 2, 'fentes', 'Fentes', 'unilateral_jambe', 'complementaire', 3, 'reps', 8, 15, 12, null, 60, 90, 'poids_du_corps', 'par jambe'),
    ('poids', 'Bas du corps', 'general', 3, 'hipthrust', 'Pont fessier', 'extension_hanche', 'complementaire', 3, 'reps', 8, 15, 12, null, 60, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Bas du corps', 'general', 4, 'mollets', 'Mollets', 'mollets', 'complementaire', 3, 'reps', 8, 15, 12, null, 45, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Push', 'force', 0, 'pompes', 'Pompes', 'poussee_horizontale', 'repere', 5, 'reps', 4, 6, 5, null, 150, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Push', 'force', 1, 'pikepushups', 'Pike push-ups', 'poussee_verticale', 'repere', 5, 'reps', 4, 6, 5, null, 150, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Push', 'force', 2, 'dips', 'Dips sur chaise', 'triceps', 'complementaire', 3, 'reps', 8, 12, 10, null, 60, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Push', 'force', 3, 'pompesdiamant', 'Pompes diamant', 'poussee_horizontale', 'complementaire', 3, 'reps', 8, 12, 10, null, 60, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Push', 'force', 4, 'pompesinclinees', 'Pompes inclinées', 'poussee_horizontale', 'complementaire', 3, 'reps', 8, 12, 10, null, 60, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Push', 'masse', 0, 'pompes', 'Pompes', 'poussee_horizontale', 'repere', 4, 'reps', 6, 12, 9, null, 60, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Push', 'masse', 1, 'pikepushups', 'Pike push-ups', 'poussee_verticale', 'repere', 4, 'reps', 6, 12, 9, null, 60, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Push', 'masse', 2, 'dips', 'Dips sur chaise', 'triceps', 'complementaire', 3, 'reps', 10, 20, 15, null, 60, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Push', 'masse', 3, 'pompesdiamant', 'Pompes diamant', 'poussee_horizontale', 'complementaire', 3, 'reps', 10, 20, 15, null, 60, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Push', 'masse', 4, 'pompesinclinees', 'Pompes inclinées', 'poussee_horizontale', 'complementaire', 3, 'reps', 10, 20, 15, null, 60, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Push', 'general', 0, 'pompes', 'Pompes', 'poussee_horizontale', 'repere', 3, 'reps', 8, 15, 12, null, 60, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Push', 'general', 1, 'pikepushups', 'Pike push-ups', 'poussee_verticale', 'repere', 3, 'reps', 8, 15, 12, null, 60, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Push', 'general', 2, 'dips', 'Dips sur chaise', 'triceps', 'complementaire', 3, 'reps', 8, 15, 12, null, 60, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Push', 'general', 3, 'pompesdiamant', 'Pompes diamant', 'poussee_horizontale', 'complementaire', 3, 'reps', 8, 15, 12, null, 60, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Push', 'general', 4, 'pompesinclinees', 'Pompes inclinées', 'poussee_horizontale', 'complementaire', 3, 'reps', 8, 15, 12, null, 60, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Pull', 'force', 0, 'superman', 'Superman', 'extension_tronc', 'repere', 5, 'reps', 4, 6, 5, null, 150, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Pull', 'force', 1, 'hipthrust', 'Pont fessier', 'extension_hanche', 'complementaire', 3, 'reps', 8, 12, 10, null, 60, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Pull', 'force', 2, 'birddog', 'Bird dog', 'gainage', 'complementaire', 3, 'reps', 8, 12, 10, null, 60, 90, 'poids_du_corps', 'par côté'),
    ('poids', 'Pull', 'force', 3, 'planche', 'Gainage', 'gainage', 'complementaire', 3, 'duree', null, null, null, 40, 45, 60, 'poids_du_corps', ''),
    ('poids', 'Pull', 'force', 4, 'planchelaterale', 'Planche latérale', 'gainage', 'complementaire', 3, 'duree', null, null, null, 30, 30, 60, 'poids_du_corps', ''),
    ('poids', 'Pull', 'masse', 0, 'superman', 'Superman', 'extension_tronc', 'repere', 4, 'reps', 6, 12, 9, null, 45, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Pull', 'masse', 1, 'hipthrust', 'Pont fessier', 'extension_hanche', 'complementaire', 3, 'reps', 10, 20, 15, null, 60, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Pull', 'masse', 2, 'birddog', 'Bird dog', 'gainage', 'complementaire', 3, 'reps', 10, 20, 15, null, 60, 90, 'poids_du_corps', 'par côté'),
    ('poids', 'Pull', 'masse', 3, 'planche', 'Gainage', 'gainage', 'complementaire', 3, 'duree', null, null, null, 40, 45, 60, 'poids_du_corps', ''),
    ('poids', 'Pull', 'masse', 4, 'planchelaterale', 'Planche latérale', 'gainage', 'complementaire', 3, 'duree', null, null, null, 30, 30, 60, 'poids_du_corps', ''),
    ('poids', 'Pull', 'general', 0, 'superman', 'Superman', 'extension_tronc', 'repere', 3, 'reps', 8, 15, 12, null, 45, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Pull', 'general', 1, 'hipthrust', 'Pont fessier', 'extension_hanche', 'complementaire', 3, 'reps', 8, 15, 12, null, 60, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Pull', 'general', 2, 'birddog', 'Bird dog', 'gainage', 'complementaire', 3, 'reps', 8, 15, 12, null, 60, 90, 'poids_du_corps', 'par côté'),
    ('poids', 'Pull', 'general', 3, 'planche', 'Gainage', 'gainage', 'complementaire', 3, 'duree', null, null, null, 40, 45, 60, 'poids_du_corps', ''),
    ('poids', 'Pull', 'general', 4, 'planchelaterale', 'Planche latérale', 'gainage', 'complementaire', 3, 'duree', null, null, null, 30, 30, 60, 'poids_du_corps', ''),
    ('poids', 'Cardio / HIIT', 'force', 0, 'burpees', 'Burpees', 'cardio', 'complementaire', 4, 'reps', 15, 15, 15, null, 45, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Cardio / HIIT', 'force', 1, 'skaters', 'Skaters', 'cardio', 'complementaire', 5, 'duree', null, null, null, 40, 30, 60, null, ''),
    ('poids', 'Cardio / HIIT', 'force', 2, 'mountainclimbers', 'Mountain climbers', 'cardio', 'complementaire', 4, 'duree', null, null, null, 30, 30, 60, null, ''),
    ('poids', 'Cardio / HIIT', 'force', 3, 'jumpingjacks', 'Jumping jacks', 'cardio', 'complementaire', 4, 'duree', null, null, null, 40, 20, 60, null, ''),
    ('poids', 'Cardio / HIIT', 'force', 4, 'squatsaute', 'Squats sautés', 'pliometrie', 'complementaire', 4, 'reps', 20, 20, 20, null, 45, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Cardio / HIIT', 'masse', 0, 'burpees', 'Burpees', 'cardio', 'complementaire', 4, 'reps', 15, 15, 15, null, 45, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Cardio / HIIT', 'masse', 1, 'skaters', 'Skaters', 'cardio', 'complementaire', 5, 'duree', null, null, null, 40, 30, 60, null, ''),
    ('poids', 'Cardio / HIIT', 'masse', 2, 'mountainclimbers', 'Mountain climbers', 'cardio', 'complementaire', 4, 'duree', null, null, null, 30, 30, 60, null, ''),
    ('poids', 'Cardio / HIIT', 'masse', 3, 'jumpingjacks', 'Jumping jacks', 'cardio', 'complementaire', 4, 'duree', null, null, null, 40, 20, 60, null, ''),
    ('poids', 'Cardio / HIIT', 'masse', 4, 'squatsaute', 'Squats sautés', 'pliometrie', 'complementaire', 4, 'reps', 20, 20, 20, null, 45, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Cardio / HIIT', 'general', 0, 'burpees', 'Burpees', 'cardio', 'complementaire', 4, 'reps', 15, 15, 15, null, 45, 90, 'poids_du_corps', 'reps'),
    ('poids', 'Cardio / HIIT', 'general', 1, 'skaters', 'Skaters', 'cardio', 'complementaire', 5, 'duree', null, null, null, 40, 30, 60, null, ''),
    ('poids', 'Cardio / HIIT', 'general', 2, 'mountainclimbers', 'Mountain climbers', 'cardio', 'complementaire', 4, 'duree', null, null, null, 30, 30, 60, null, ''),
    ('poids', 'Cardio / HIIT', 'general', 3, 'jumpingjacks', 'Jumping jacks', 'cardio', 'complementaire', 4, 'duree', null, null, null, 40, 20, 60, null, ''),
    ('poids', 'Cardio / HIIT', 'general', 4, 'squatsaute', 'Squats sautés', 'pliometrie', 'complementaire', 4, 'reps', 20, 20, 20, null, 45, 90, 'poids_du_corps', 'reps')
),
cible as (
  select ps.id as etape_id,
         case when ps.nom in ('Full Body', 'Haut du corps', 'Bas du corps', 'Push', 'Pull', 'Cardio / HIIT') then ps.nom else 'Full Body' end as etape,
         case when c.lieu = 'salle' then 'salle' when c.materiel = 'halteres' then 'halteres' else 'poids' end as lieu,
         /* `orientationDe` : la force d'abord, puis la masse, sinon général. */
         case when lower(coalesce(pr.onboarding_goals::text, '')) like '%force%' then 'force'
              when lower(coalesce(pr.onboarding_goals::text, '')) like '%masse%' then 'masse'
              else 'general' end as orientation,
         pr.onboarding_level as niveau
    from public.programmes p
    join public.programme_seances ps on ps.programme_id = p.id
    left join public.contexte_entrainement c on c.user_id = p.user_id
    left join public.profiles pr on pr.id = p.user_id
   where p.statut = 'actif'
),
modeles as (
  insert into public.etape_modeles (programme_seance_id, lieu, orientation, niveau, composition_version)
  select etape_id, lieu, orientation, niveau, 1 from cible
  on conflict (programme_seance_id, lieu) do nothing
  returning id, programme_seance_id, lieu, orientation
)
insert into public.etape_exercices (
  modele_id, emplacement, exercice_cle, exercice_nom, fonction, statut, series, mesure,
  reps_min, reps_max, reps_cible, duree_s, repos_s, transition_s, charge_type, unite
)
select m.id, b.emplacement, b.exercice_cle, b.exercice_nom, b.fonction, b.statut, b.series, b.mesure,
       b.reps_min, b.reps_max, b.reps_cible, b.duree_s, b.repos_s, b.transition_s, b.charge_type, b.unite
  from modeles m
  join cible c on c.etape_id = m.programme_seance_id and c.lieu = m.lieu
  join banque b on b.lieu = c.lieu and b.etape = c.etape and b.orientation = m.orientation;
